# action.yml
name: 'BllokHub'
description: 'Generate a blog from github issues'
branding:
  icon: 'align-left'
  color: 'red'
inputs:
  githubToken:  # your github developer token
    description: 'your github developer token'
    required: true
    default: ''
  githubOwner:  # your github username
    description: 'your github username'
    required: true
    default: ''
  githubRepo:  # your github repo
    description: 'your github repo'
    required: true
    default: ''
outputs:
  bllok-status: # id of output
    description: 'The status of the job'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.githubToken }}
    - ${{ inputs.githubOwner }}
    - ${{ inputs.githubRepo }}