name: GenerateBlog
on:
  workflow_dispatch:
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Generate website from issues
    steps:
      - name: Generate
        id: generate
        uses: eltonkola/bllok@0.0.3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          githubOwner: ${{ github.repository.owner }}
          githubRepo: ${{ github.repository.name }}
      # Use the output from the `hello` step
      - name: Get the output status
        run: echo "The status was ${{ steps.generate.outputs.bllok-status }}"
